name: Noctis
version: ${project.version}
main: com.gmail.ceezuns.noctis.Noctis
api-version: 1.13
authors: [ceezuns]
website: ceezuns.cf

commands:
  markers:
    description: Markers Command
  cobble:
    description: Cobble Command
  graves:
    description: Graves Command
  pin:
    description: Pin Command
  ores:
    description: Ores Command
  protection:
    description: Protection Command
    permission: protection.command